version: '3.8'

services:
  backend:
    build: ./backend  
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/courses_api
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1 
  frontend:
    build: ./frontend  
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: npm start  
